#pragma checksum "..\..\..\FollowBotGui.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D611E3F791AB0739B4214255720FFBC7FD7A7025530E0256E89D0D9F60AA6964"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot {
    
    
    /// <summary>
    /// FollowBotGui
    /// </summary>
    public partial class FollowBotGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 163 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlUltimatumLootTimer;
        
        #line default
        #line hidden
        
        
        #line 525 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DebugStatementsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 529 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LevelOffhandOnly;
        
        #line default
        #line hidden
        
        
        #line 535 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LevelAllGems;
        
        #line default
        #line hidden
        
        
        #line 559 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GlobalNameIgnoreTextBox;
        
        #line default
        #line hidden
        
        
        #line 563 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 570 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox GlobalNameIgnoreListListBox;
        
        #line default
        #line hidden
        
        
        #line 783 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlFPS;
        
        #line default
        #line hidden
        
        
        #line 796 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbFPS;
        
        #line default
        #line hidden
        
        
        #line 811 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlXPos;
        
        #line default
        #line hidden
        
        
        #line 824 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbXPos;
        
        #line default
        #line hidden
        
        
        #line 839 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlYPos;
        
        #line default
        #line hidden
        
        
        #line 852 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbYPos;
        
        #line default
        #line hidden
        
        
        #line 867 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlTransparency;
        
        #line default
        #line hidden
        
        
        #line 880 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbTransparency;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/followbotgui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\FollowBotGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SlPortOutDelay = ((System.Windows.Controls.Slider)(target));
            return;
            case 2:
            this.TbPortOutDelay = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.SlUltimatumLootTimer = ((System.Windows.Controls.Slider)(target));
            return;
            case 4:
            
            #line 267 "..\..\..\FollowBotGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ChangeStance_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DebugStatementsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.LevelOffhandOnly = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.LevelAllGems = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.GlobalNameIgnoreTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.AddGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 569 "..\..\..\FollowBotGui.xaml"
            this.AddGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.AddGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 11:
            this.RemoveGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 576 "..\..\..\FollowBotGui.xaml"
            this.RemoveGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.RemoveGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.GlobalNameIgnoreListListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 588 "..\..\..\FollowBotGui.xaml"
            this.GlobalNameIgnoreListListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GlobalNameIgnoreListListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.SlFPS = ((System.Windows.Controls.Slider)(target));
            return;
            case 14:
            this.TbFPS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SlXPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 16:
            this.TbXPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.SlYPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 18:
            this.TbYPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.SlTransparency = ((System.Windows.Controls.Slider)(target));
            return;
            case 20:
            this.TbTransparency = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 5:
            
            #line 511 "..\..\..\FollowBotGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemoveDefensiveSkillRule);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

