#pragma checksum "..\..\..\FollowBotGui.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7E33522A86D7283BA91A9D4350508F472694CBC82688A86FB3B555EE86FE1A05"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot {
    
    
    /// <summary>
    /// FollowBotGui
    /// </summary>
    public partial class FollowBotGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 135 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 486 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DebugStatementsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 490 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LevelOffhandOnly;
        
        #line default
        #line hidden
        
        
        #line 496 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LevelAllGems;
        
        #line default
        #line hidden
        
        
        #line 520 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GlobalNameIgnoreTextBox;
        
        #line default
        #line hidden
        
        
        #line 524 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 544 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox GlobalNameIgnoreListListBox;
        
        #line default
        #line hidden
        
        
        #line 735 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlFPS;
        
        #line default
        #line hidden
        
        
        #line 748 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbFPS;
        
        #line default
        #line hidden
        
        
        #line 763 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlXPos;
        
        #line default
        #line hidden
        
        
        #line 776 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbXPos;
        
        #line default
        #line hidden
        
        
        #line 791 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlYPos;
        
        #line default
        #line hidden
        
        
        #line 804 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbYPos;
        
        #line default
        #line hidden
        
        
        #line 819 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlTransparency;
        
        #line default
        #line hidden
        
        
        #line 832 "..\..\..\FollowBotGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbTransparency;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/followbotgui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\FollowBotGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SlPortOutDelay = ((System.Windows.Controls.Slider)(target));
            return;
            case 2:
            this.TbPortOutDelay = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            
            #line 228 "..\..\..\FollowBotGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ChangeStance_OnClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.DebugStatementsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.LevelOffhandOnly = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.LevelAllGems = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.GlobalNameIgnoreTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.AddGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 530 "..\..\..\FollowBotGui.xaml"
            this.AddGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.AddGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 10:
            this.RemoveGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 537 "..\..\..\FollowBotGui.xaml"
            this.RemoveGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.RemoveGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 11:
            this.GlobalNameIgnoreListListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 549 "..\..\..\FollowBotGui.xaml"
            this.GlobalNameIgnoreListListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GlobalNameIgnoreListListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.SlFPS = ((System.Windows.Controls.Slider)(target));
            return;
            case 13:
            this.TbFPS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.SlXPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 15:
            this.TbXPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.SlYPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 17:
            this.TbYPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.SlTransparency = ((System.Windows.Controls.Slider)(target));
            return;
            case 19:
            this.TbTransparency = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 4:
            
            #line 472 "..\..\..\FollowBotGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemoveDefensiveSkillRule);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

