#pragma checksum "..\..\..\..\..\Views\Tabs\GeneralTab.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F1702D3108B300DE4A8970EB204B987F0DDF70030C509EECE556B061BEA93E3A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot.Views.Tabs {
    
    
    /// <summary>
    /// GeneralTab
    /// </summary>
    public partial class GeneralTab : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 53 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox LoginPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 238 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 287 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InviteTradeWhiteListTextBox;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddInviteTradeWhiteListButton;
        
        #line default
        #line hidden
        
        
        #line 298 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveInviteTradeWhiteListButton;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox InviteTradeWhiteListListBox;
        
        #line default
        #line hidden
        
        
        #line 344 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton BlacklistByName;
        
        #line default
        #line hidden
        
        
        #line 347 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton BlacklistByMetadata;
        
        #line default
        #line hidden
        
        
        #line 354 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LootBlacklistTextBox;
        
        #line default
        #line hidden
        
        
        #line 359 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddLootBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveLootBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LootBlacklistListBox;
        
        #line default
        #line hidden
        
        
        #line 394 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlUltimatumLootTimer;
        
        #line default
        #line hidden
        
        
        #line 416 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TradeSlotGrid;
        
        #line default
        #line hidden
        
        
        #line 482 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox GemColorComboBox;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TestSmartLogicButton;
        
        #line default
        #line hidden
        
        
        #line 525 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox DivineFontOptionsListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/views/tabs/generaltab.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LoginPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 55 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.LoginPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.LoginPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SlPortOutDelay = ((System.Windows.Controls.Slider)(target));
            return;
            case 3:
            this.TbPortOutDelay = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.InviteTradeWhiteListTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.AddInviteTradeWhiteListButton = ((System.Windows.Controls.Button)(target));
            
            #line 297 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddInviteTradeWhiteListButton.Click += new System.Windows.RoutedEventHandler(this.AddInviteTradeWhiteListButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.RemoveInviteTradeWhiteListButton = ((System.Windows.Controls.Button)(target));
            
            #line 304 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RemoveInviteTradeWhiteListButton.Click += new System.Windows.RoutedEventHandler(this.RemoveInviteTradeWhiteListButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.InviteTradeWhiteListListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 316 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.InviteTradeWhiteListListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.InviteTradeWhiteListListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BlacklistByName = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 9:
            this.BlacklistByMetadata = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 10:
            this.LootBlacklistTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.AddLootBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 360 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddLootBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.AddLootBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.RemoveLootBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 363 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RemoveLootBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.RemoveLootBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 13:
            this.LootBlacklistListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 373 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.LootBlacklistListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.LootBlacklistListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.SlUltimatumLootTimer = ((System.Windows.Controls.Slider)(target));
            return;
            case 15:
            this.TradeSlotGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            
            #line 442 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearAllSlots_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 443 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExcludeLeftColumn_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.GemColorComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 484 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.GemColorComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GemColorComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TestSmartLogicButton = ((System.Windows.Controls.Button)(target));
            
            #line 487 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.TestSmartLogicButton.Click += new System.Windows.RoutedEventHandler(this.TestSmartLogicButton_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.DivineFontOptionsListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 528 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.DivineFontOptionsListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DivineFontOptionsListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 21:
            
            #line 569 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveDivineFontOptionUp_Click);
            
            #line default
            #line hidden
            break;
            case 22:
            
            #line 576 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveDivineFontOptionDown_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

