#pragma checksum "..\..\..\..\..\Views\Tabs\GeneralTab.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "E3EE568394A4B64EFE50D139E935634B14D4E543D1A586B7B372FC40AF388664"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot.Views.Tabs {
    
    
    /// <summary>
    /// GeneralTab
    /// </summary>
    public partial class GeneralTab : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 53 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox LoginPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 313 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 326 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbPortOutDelay;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentAreaIdTextBlock;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddCurrentAreaButton;
        
        #line default
        #line hidden
        
        
        #line 377 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RefreshAreaIdsButton;
        
        #line default
        #line hidden
        
        
        #line 390 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LeaderAreaIdTextBlock;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddLeaderAreaButton;
        
        #line default
        #line hidden
        
        
        #line 411 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TeleportBlacklistTextBox;
        
        #line default
        #line hidden
        
        
        #line 415 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddTeleportBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveTeleportBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 435 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox TeleportBlacklistListBox;
        
        #line default
        #line hidden
        
        
        #line 539 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InviteTradeWhiteListTextBox;
        
        #line default
        #line hidden
        
        
        #line 543 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddInviteTradeWhiteListButton;
        
        #line default
        #line hidden
        
        
        #line 550 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveInviteTradeWhiteListButton;
        
        #line default
        #line hidden
        
        
        #line 563 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox InviteTradeWhiteListListBox;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton BlacklistByName;
        
        #line default
        #line hidden
        
        
        #line 599 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton BlacklistByMetadata;
        
        #line default
        #line hidden
        
        
        #line 606 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LootBlacklistTextBox;
        
        #line default
        #line hidden
        
        
        #line 611 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddLootBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 614 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveLootBlacklistButton;
        
        #line default
        #line hidden
        
        
        #line 622 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LootBlacklistListBox;
        
        #line default
        #line hidden
        
        
        #line 651 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlUltimatumUnloaderDelay;
        
        #line default
        #line hidden
        
        
        #line 662 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlUltimatumLootTimer;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox WishPriorityTextBox;
        
        #line default
        #line hidden
        
        
        #line 697 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox WishPriorityListBox;
        
        #line default
        #line hidden
        
        
        #line 736 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TradeSlotGrid;
        
        #line default
        #line hidden
        
        
        #line 814 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox GemColorComboBox;
        
        #line default
        #line hidden
        
        
        #line 817 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TestSmartLogicButton;
        
        #line default
        #line hidden
        
        
        #line 857 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox DivineFontOptionsListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/views/tabs/generaltab.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LoginPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 55 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.LoginPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.LoginPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SlPortOutDelay = ((System.Windows.Controls.Slider)(target));
            return;
            case 3:
            this.TbPortOutDelay = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.CurrentAreaIdTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.AddCurrentAreaButton = ((System.Windows.Controls.Button)(target));
            
            #line 376 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddCurrentAreaButton.Click += new System.Windows.RoutedEventHandler(this.AddCurrentAreaButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.RefreshAreaIdsButton = ((System.Windows.Controls.Button)(target));
            
            #line 383 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RefreshAreaIdsButton.Click += new System.Windows.RoutedEventHandler(this.RefreshAreaIdsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.LeaderAreaIdTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.AddLeaderAreaButton = ((System.Windows.Controls.Button)(target));
            
            #line 404 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddLeaderAreaButton.Click += new System.Windows.RoutedEventHandler(this.AddLeaderAreaButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TeleportBlacklistTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.AddTeleportBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 421 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddTeleportBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.AddTeleportBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 11:
            this.RemoveTeleportBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 428 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RemoveTeleportBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.RemoveTeleportBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.TeleportBlacklistListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 440 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.TeleportBlacklistListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TeleportBlacklistListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 503 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddPassiveTreeUrl_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.InviteTradeWhiteListTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.AddInviteTradeWhiteListButton = ((System.Windows.Controls.Button)(target));
            
            #line 549 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddInviteTradeWhiteListButton.Click += new System.Windows.RoutedEventHandler(this.AddInviteTradeWhiteListButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 17:
            this.RemoveInviteTradeWhiteListButton = ((System.Windows.Controls.Button)(target));
            
            #line 556 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RemoveInviteTradeWhiteListButton.Click += new System.Windows.RoutedEventHandler(this.RemoveInviteTradeWhiteListButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 18:
            this.InviteTradeWhiteListListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 568 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.InviteTradeWhiteListListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.InviteTradeWhiteListListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.BlacklistByName = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 20:
            this.BlacklistByMetadata = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 21:
            this.LootBlacklistTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.AddLootBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 612 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.AddLootBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.AddLootBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RemoveLootBlacklistButton = ((System.Windows.Controls.Button)(target));
            
            #line 615 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.RemoveLootBlacklistButton.Click += new System.Windows.RoutedEventHandler(this.RemoveLootBlacklistButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 24:
            this.LootBlacklistListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 625 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.LootBlacklistListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.LootBlacklistListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.SlUltimatumUnloaderDelay = ((System.Windows.Controls.Slider)(target));
            return;
            case 26:
            this.SlUltimatumLootTimer = ((System.Windows.Controls.Slider)(target));
            return;
            case 27:
            this.WishPriorityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            
            #line 691 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddWishPriority_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 692 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemoveWishPriority_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 693 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResetWishPriority_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.WishPriorityListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 700 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.WishPriorityListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.WishPriorityListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 34:
            this.TradeSlotGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 35:
            
            #line 762 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearAllSlots_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            
            #line 763 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExcludeLeftColumn_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.GemColorComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 816 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.GemColorComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GemColorComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 38:
            this.TestSmartLogicButton = ((System.Windows.Controls.Button)(target));
            
            #line 819 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.TestSmartLogicButton.Click += new System.Windows.RoutedEventHandler(this.TestSmartLogicButton_Click);
            
            #line default
            #line hidden
            return;
            case 39:
            this.DivineFontOptionsListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 860 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            this.DivineFontOptionsListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DivineFontOptionsListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 13:
            
            #line 495 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemovePassiveTreeUrl_Click);
            
            #line default
            #line hidden
            break;
            case 32:
            
            #line 711 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveWishUp_Click);
            
            #line default
            #line hidden
            break;
            case 33:
            
            #line 712 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveWishDown_Click);
            
            #line default
            #line hidden
            break;
            case 40:
            
            #line 901 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveDivineFontOptionUp_Click);
            
            #line default
            #line hidden
            break;
            case 41:
            
            #line 908 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveDivineFontOptionDown_Click);
            
            #line default
            #line hidden
            break;
            case 42:
            
            #line 932 "..\..\..\..\..\Views\Tabs\GeneralTab.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BrowseGemNames_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

