#pragma checksum "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "E6F64046F8C2DEA422CBA1110365F78E3DC0255432C6D13EA0C763EEC1E525E5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot.Views.Tabs {
    
    
    /// <summary>
    /// LevelGemsTab
    /// </summary>
    public partial class LevelGemsTab : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DebugStatementsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LevelGems;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox UseLevelAllButton;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GlobalNameIgnoreTextBox;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox GlobalNameIgnoreListListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/views/tabs/levelgemstab.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DebugStatementsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.LevelGems = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.UseLevelAllButton = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.GlobalNameIgnoreTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.AddGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 52 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
            this.AddGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.AddGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.RemoveGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 59 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
            this.RemoveGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.RemoveGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.GlobalNameIgnoreListListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 71 "..\..\..\..\..\Views\Tabs\LevelGemsTab.xaml"
            this.GlobalNameIgnoreListListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GlobalNameIgnoreListListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

