#pragma checksum "..\..\..\..\..\Views\Tabs\OverlayTab.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "AAFB60421E6F04E4A4738F10EDEF1A89C9D0A146D0A79EDBB363A19B425955DB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FollowBot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FollowBot.Views.Tabs {
    
    
    /// <summary>
    /// OverlayTab
    /// </summary>
    public partial class OverlayTab : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 73 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlFPS;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbFPS;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlXPos;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbXPos;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlYPos;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbYPos;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SlTransparency;
        
        #line default
        #line hidden
        
        
        #line 170 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbTransparency;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FollowBot;component/views/tabs/overlaytab.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Tabs\OverlayTab.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SlFPS = ((System.Windows.Controls.Slider)(target));
            return;
            case 2:
            this.TbFPS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.SlXPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 4:
            this.TbXPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.SlYPos = ((System.Windows.Controls.Slider)(target));
            return;
            case 6:
            this.TbYPos = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.SlTransparency = ((System.Windows.Controls.Slider)(target));
            return;
            case 8:
            this.TbTransparency = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

